name: Build snapshot

on:
  push:
    branches:
      - "**"
    tags:
      - "!**"
  workflow_dispatch:

jobs:
  snapshot:
    uses: ./.github/workflows/build.yaml
    secrets: inherit
    with:
      linux-appimage: true
