name: Build Linux builder images

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
      - '.github/workflows/linux-builder.yaml'
      - 'build/linux/wails.Dockerfile'
      - 'build/linux/build-nuga.sh'
      - 'build/linux/pack-appimage.sh'

jobs:
  arm64:
    name: Build aarch64 image builder
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build image
        run: make linux-builder/image-arm64
      - name: Push image
        run: make linux-builder/push-image-arm64
  amd64:
    name: Build amd64 image builder
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build image
        run: make linux-builder/image-amd64
      - name: Push image
        run: make linux-builder/push-image-amd64
  appimage:
    name: Build appimage builder
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build image
        run: make linux-builder/image-appimage
      - name: Push image
        run: make linux-builder/push-image-appimage
