name: Quality assurance

on:
  - push
  - workflow_dispatch

env:
  GO_VERSION: '1.21.4'
  PNPM_VERSION: '8.13.1'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: go.sum
      - uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}
      - name: Install C/C++ deps
        run: sudo apt install libudev-dev -y
      - name: Install frontend deps
        run: |
          cd frontend
          pnpm install --frozen-lockfile
          cd ../..
      - name: Create dummy dist dir
        run: |
          mkdir -p frontend/dist
          echo "." > frontend/dist/.gitkeep
      - name: Install go deps
        run: go mod tidy
      - name: Lint with golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --config=./.golangci.yaml
          skip-cache: true
      - name: Lint with revive
        uses: docker://morphy/revive-action:v2
        with:
          config: revive.toml
          path: "./..."
      - name: Lint frontend scripts
        run: |
          cd frontend
          pnpm run lint:scripts
      - name: Lint frontend styles
        run: |
          cd frontend
          pnpm run lint:styles
